apiVersion: v1
kind: Namespace
metadata:
  name: secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hello
  namespace: default
spec:
  dataFrom:
  - extract:
      key: /dev/meh
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: dev
  target:
    name: hello
    template:
      data:
        config.yml: |
          - https://{{ .user }}:{{ .password }}@api.exmaple.com
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: kyverno-sync-secrets
spec:
  rules:
  - generate:
      apiVersion: v1
      clone:
        name: kuma-zone-kds-ca-certs
        namespace: secrets
      kind: Secret
      name: kds-ca-certs
      namespace: '{{request.object.metadata.name}}'
      synchronize: true
    match:
      any:
      - resources:
          kinds:
          - Namespace
          names:
          - kuma
    name: kuma-zone-kds-ca-certs
  - generate:
      apiVersion: v1
      clone:
        name: kuma-zone-kuma-tls-cert
        namespace: secrets
      kind: Secret
      name: kuma-tls-cert
      namespace: '{{request.object.metadata.name}}'
      synchronize: true
    match:
      any:
      - resources:
          kinds:
          - Namespace
          names:
          - kuma
    name: kuma-zone-kuma-tls-cert
---
apiVersion: v1
kind: Pod
metadata:
  name: secrets
  namespace: secrets
spec:
  containers:
  - args:
    - sleep infinity
    command:
    - bash
    - -c
    image: ubuntu
    name: sleep
    volumeMounts:
    - mountPath: /mnt/secrets/kuma-zone-kds-ca-certs
      name: kuma-zone-kds-ca-certs
      readOnly: true
    - mountPath: /mnt/secrets/kuma-zone-kuma-tls-cert
      name: kuma-zone-kuma-tls-cert
      readOnly: true
  volumes:
  - name: kuma-zone-kds-ca-certs
    secret:
      optional: false
      secretName: kuma-zone-kds-ca-certs
  - name: kuma-zone-kuma-tls-cert
    secret:
      optional: false
      secretName: kuma-zone-kuma-tls-cert
