#ManagedBy: cue

apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: external-secrets
spec:
  provider:
    vault:
      server: http://100.107.114.21:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: vcluster-control-vc4
          role: external-secrets
