#ManagedBy: cue

patchesStrategicMerge: []
resources: []
helmCharts:
  - releaseName: pod-identity-webhook
    name: amazon-eks-pod-identity-webhook
    version: 1.0.3
    repo: https://jkroepke.github.io/helm-charts
    valuesInline: {}
    includeCRDs: true
