apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: dev
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: amanibhavam-control-vc2
          role: external-secrets
      path: kv
      server: http://100.107.114.21:8200
      version: v2
