repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(provider|cdktf.out|.local)/|\.lock|charts
      - id: end-of-file-fixer
        exclude: ^(provider|cdktf.out|.local)/|\.lock|charts
      - id: check-json
        exclude: ^(provider|cdktf.out|.local)/
      - id: check-yaml
        args: [--allow-multiple-documents, --unsafe]
        exclude: ^(provider|cdktf.out|.local)/|charts
      - id: check-toml
        exclude: ^(provider|cdktf.out|.local)/|charts
      - id: check-shebang-scripts-are-executable
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
