repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(provider|cdktf.out|.local)/|\.lock|charts|/out/
      - id: end-of-file-fixer
        exclude: ^(provider|cdktf.out|.local)/|\.lock|charts|/out/|main.tf.json
      - id: check-json
        exclude: ^(provider|cdktf.out|.local)/|/out/
      - id: check-yaml
        args: [--allow-multiple-documents, --unsafe]
        exclude: ^(provider|cdktf.out|.local)/|charts|/out/
      - id: check-toml
        exclude: ^(provider|cdktf.out|.local)/|charts|/out/
      - id: check-shebang-scripts-are-executable
        exclude: ^(provider|cdktf.out|.local)/|charts|/out/
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        exclude: ^(provider|cdktf.out|.local)/|charts|/out/|main.tf.json|^k/
