#!/usr/bin/env bash

# assumes running from $HOME

function main {
	source ~/.bash_profile

	if ! test -d ~/work; then
		(cd && bin/persist-cache)
	fi

	mkdir -p ~/.terraform.d/plugin-cache

	mkdir -p ~/.gnupg

	(
		set +f
		rsync -ia ~/dotfiles/.gnupg/* ~/.gnupg/
	)

	# https://status.open-vsx.org
	local exts="
		anthropic.claude-code
		astro-build.astro-vscode
		betterthantomorrow.calva
		betterthantomorrow.joyride
		cuelang.cue
		esbenp.prettier-vscode
		golang.go
		kokakiwi.vscode-just
		ms-python.debugpy
		ms-python.python
		svelte.svelte-vscode
		vscodevim.vim
		"

	(
		code-server --list-extensions
		for a in 1 2; do for b in $exts; do echo "$b"; done; done
	) | tr A-Z a-z | sort -r | uniq -c | grep ' 2 ' | while read -r count extension; do
		cached="$(set +f; (ls -d ~/m/vsix/$extension-*.vsix 2>/dev/null || true)| head -1)"
		if test -f "${cached}"; then
			extension="${cached}"
		fi
		$(which code-server | head -1) serve-local --force --install-extension "${extension}"
	done
}

main "$@"
