apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: emojivoto
spec:
  rules:
  - host: emojivoto.chm.life
    http:
      paths:
      - backend:
          serviceName: web-svc
          servicePort: 80
