apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  name: combo-breaker
  namespace: default
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - command:
        - "false"
        image: ubuntu
        name: meh
      restartPolicy: Never
---
apiVersion: tf.isaaguilar.com/v1alpha2
kind: Terraform
metadata:
  name: chicken
  namespace: default
spec:
  backend: "terraform {\n\tbackend \"kubernetes\" {\n\t\tin_cluster_config = true\n\t\tsecret_suffix
    \    = \"chicken\"\n\t\tnamespace         = \"default\"\n\t}\n}"
  ignoreDelete: false
  keepLatestPodsOnly: true
  scmAuthMethods: []
  serviceAccount: default
  terraformModule:
    source: https://github.com/defn/app.git//tf/m/chicken?ref=master
  terraformVersion: 1.0.0
