#ManagedBy: cue

apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: external-secrets
spec:
  provider:
    vault:
      server: http://100.90.37.83:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: k3d-global
          role: external-secrets
