namespace: karpenter

helmCharts:
- releaseName: karpenter
  name: karpenter
  version: 0.16.3
  repo:  https://charts.karpenter.sh
  includeCRDs: true
  valuesInline:
    clusterName: k3d-control
    clusterEndpoint: https://kubernetes.default.svc.cluster.local
    controller:
      env:
        - name: AWS_REGION
          value: us-west-1
    webhook:
      env:
        - name: AWS_REGION
          value: us-west-1
