apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: vc1
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["t3.medium", "t3a.medium"]
  limits:
    resources:
      cpu: 2
  labels:
    env: vc1
  taints:
    - key: env
      value: vc1
      effect: NoSchedule
  providerRef:
    name: default
  ttlSecondsAfterEmpty: 30
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: vc2
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["t3.medium", "t3a.medium"]
  limits:
    resources:
      cpu: 2
  labels:
    env: vc2
  taints:
    - key: env
      value: vc2
      effect: NoSchedule
  providerRef:
    name: default
  ttlSecondsAfterEmpty: 30