apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: vc2
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: kubernetes.io/arch
      operator: In
      values: ["amd64"]
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["m3.medium", "m1.medium", "t3.medium", "t3a.medium"]
  limits:
    resources:
      cpu: "2"
  labels:
    env: vc2
  taints:
    - key: env
      value: vc2
      effect: NoSchedule
  providerRef:
    name: default
  ttlSecondsAfterEmpty: 1800
