apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hello
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: external-secrets
    kind: ClusterSecretStore
  target:
    name: hello
    template:
      data:
        world: "{{ .world | toString }}"
        meh: "{{ .meh | toString }}"
  dataFrom:
    - extract:
        key: hello/earth
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::319951235442:role/meh"
    eks.amazonaws.com/sts-regional-endpoints: "true"
    eks.amazonaws.com/token-expiration: "3600"
---
apiVersion: v1
kind: Pod
metadata:
  name: hello
  namespace: default
spec:
  serviceAccountName: hello
  containers:
    - name: hello
      image: ghcr.io/defn/dev:latest-nix-installed
      command: ["bash", "-c"]
      args: ["sudo apt update; sudo apt install -y awscli; aws sts get-caller-identity | sudo tee /mnt/hello.txt; sleep infinity"]
      volumeMounts:
      - name: hello
        mountPath: /mnt/hello
        readOnly: true
  volumes:
    - name: hello
      secret:
        secretName: hello
        optional: false
