apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    networking.knative.dev/visibility: cluster-local
  name: hello
  namespace: default
spec:
  template:
    spec:
      containerConcurrency: 0
      containers:
      - name: hello
        image: containous/whoami:latest
        ports:
        - containerPort: 80
  traffic:
  - latestRevision: true
    percent: 100
  tolerations:
    - key: env
      value: vc1
      operator: Equal
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: env
            operator: In
            values:
            - vc1