apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: dex
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dex
    app.kubernetes.io/version: 2.32.0
    helm.sh/chart: dex-0.9.0
  name: dex
  namespace: dex
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/instance: dex
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dex
    app.kubernetes.io/version: 2.32.0
    helm.sh/chart: dex-0.9.0
  name: dex
  namespace: dex
rules:
- apiGroups:
  - dex.coreos.com
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: dex
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dex
    app.kubernetes.io/version: 2.32.0
    helm.sh/chart: dex-0.9.0
  name: dex
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: dex
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dex
    app.kubernetes.io/version: 2.32.0
    helm.sh/chart: dex-0.9.0
  name: dex
  namespace: dex
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dex
subjects:
- kind: ServiceAccount
  name: dex
  namespace: dex
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: dex
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dex
    app.kubernetes.io/version: 2.32.0
    helm.sh/chart: dex-0.9.0
  name: dex-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dex
subjects:
- kind: ServiceAccount
  name: dex
  namespace: dex
---
apiVersion: v1
data:
  config.yaml: Y29ubmVjdG9yczoKLSBjb25maWc6CiAgICBjbGllbnRJRDogR0lUSFVCX0NMSUVOVF9JRAogICAgY2xpZW50U2VjcmV0OiBHSVRIVUJfQ0xJRU5UX1NFQ1JFVAogICAgcmVkaXJlY3RVUkk6IGh0dHA6Ly9sb2NhbGhvc3Q6NTU1Ni9jYWxsYmFjawogIGlkOiBnaXRodWIKICBuYW1lOiBHaXRIdWIKICB0eXBlOiBnaXRodWIKZW5hYmxlUGFzc3dvcmREQjogdHJ1ZQppc3N1ZXI6IGh0dHBzOi8vZGV4LnJlbW9jYWwubmV0Cm9hdXRoMjoKICBza2lwQXBwcm92YWxTY3JlZW46IHRydWUKc3RhdGljQ2xpZW50czoKLSBpZDogZm9yd2FyZC1hdXRoCiAgbmFtZTogVHJhZWZpayBGb3J3YXJkIEF1dGgKICByZWRpcmVjdFVSSXM6CiAgLSBodHRwczovL2F1dGgucmVtb2NhbC5uZXQvX29hdXRoCiAgc2VjcmV0OiA2YmJjM2YyYTZkNTVhMzkxN2UwNjhkZmY1YjA3YTQ3NgpzdGF0aWNQYXNzd29yZHM6Ci0gZW1haWw6IGlhbUBkZWZuLnNoCiAgaGFzaDogJDJhJDEwJDJiMmNVOENQaE9UYUdyczFIUlF1QXVlUzdKVFQ1WkhzSFN6WWlGUG0xbGVaY2s3TWM4VDRXCiAgdXNlcmlkOiAiMTIzNDU2Nzg5IgogIHVzZXJuYW1lOiBhZG1pbgpzdG9yYWdlOgogIHR5cGU6IG1lbW9yeQp3ZWI6CiAgaHR0cDogMC4wLjAuMDo1NTU2
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: dex
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dex
    app.kubernetes.io/version: 2.32.0
    helm.sh/chart: dex-0.9.0
  name: dex
  namespace: dex
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: dex
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dex
    app.kubernetes.io/version: 2.32.0
    helm.sh/chart: dex-0.9.0
  name: dex
  namespace: dex
spec:
  ports:
  - appProtocol: http
    name: http
    port: 5556
    protocol: TCP
    targetPort: http
  - appProtocol: http
    name: telemetry
    port: 5558
    protocol: TCP
    targetPort: telemetry
  selector:
    app.kubernetes.io/instance: dex
    app.kubernetes.io/name: dex
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: dex
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dex
    app.kubernetes.io/version: 2.32.0
    helm.sh/chart: dex-0.9.0
  name: dex
  namespace: dex
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: dex
      app.kubernetes.io/name: dex
  template:
    metadata:
      annotations:
        checksum/config: 926523734585da6cf28d5a2e98c7ffd81677277bd0db8a64958cb182cc440d39
      labels:
        app.kubernetes.io/instance: dex
        app.kubernetes.io/name: dex
    spec:
      containers:
      - args:
        - dex
        - serve
        - --web-http-addr
        - 0.0.0.0:5556
        - --telemetry-addr
        - 0.0.0.0:5558
        - /etc/dex/config.yaml
        env: null
        image: ghcr.io/dexidp/dex:v2.32.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: telemetry
        name: dex
        ports:
        - containerPort: 5556
          name: http
          protocol: TCP
        - containerPort: 5558
          name: telemetry
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: telemetry
        resources: {}
        securityContext: {}
        volumeMounts:
        - mountPath: /etc/dex
          name: config
          readOnly: true
      securityContext: {}
      serviceAccountName: dex
      volumes:
      - name: config
        secret:
          secretName: dex
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ts-dex-websecure
  namespace: dex
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: HostRegexp(`dex.{dom:.+}`)
    services:
    - name: dex
      port: 5556
  tls:
    secretName: default-certificate
