# ManagedBy: cue

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: k3d-smiley
spec:
  project: default
  destination:
    name: in-cluster
  source:
    repoURL: https://github.com/defn/app
    targetRevision: master
    path: e/k3d-smiley
  syncPolicy:
    automated:
      prune: true
