apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k3d-control
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/defn/app
    path: e/k3d-control
    targetRevision: master
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
