apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vc4
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/defn/app
    path: e/vc4
    targetRevision: master
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
