apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    networking.knative.dev/visibility: cluster-local
  annotations:
    networking.knative.dev/ingress.class: kong
  name: hello
  namespace: default
spec:
  template:
    spec:
      metadata:
		    annotations: 
          kuma.io/sidecar-injection: "enabled"
          kuma.io/virtual-probes: "disabled"
          traffic.kuma.io/exclude-inbound-ports:  "8012"
      containerConcurrency: 0
      containers:
      - name: whoami
        image: containous/whoami:latest
        ports:
        - containerPort: 80
  traffic:
  - latestRevision: true
    percent: 100
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    networking.knative.dev/visibility: cluster-local
  annotations:
    networking.knative.dev/ingress.class: kong
  name: bye
  namespace: default
spec:
  template:
    spec:
      containerConcurrency: 0
      containers:
      - name: whoami
        image: containous/whoami:latest
        ports:
        - containerPort: 80
  traffic:
  - latestRevision: true
    percent: 100
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    networking.knative.dev/visibility: cluster-local
  name: hi
  namespace: default
spec:
  template:
    spec:
      containerConcurrency: 0
      containers:
      - name: whoami
        image: containous/whoami:latest
        ports:
        - containerPort: 80
      tolerations:
        - key: env
          value: vc2
          operator: Equal
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: env
                operator: In
                values:
                - vc2
  traffic:
  - latestRevision: true
    percent: 100
