apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: k3d-control-cert-manager
  namespace: argocd
spec:
  destination:
    name: k3d-control
  ignoreDifferences:
  - group: ""
    jsonPointers:
    - /data
    kind: Secret
    name: karpenter-cert
    namespace: karpenter
  project: default
  source:
    path: k/cert-manager
    repoURL: https://github.com/amanibhavam/dotfiles
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: k3d-control-external-secrets-operator
  namespace: argocd
spec:
  destination:
    name: k3d-control
  ignoreDifferences:
  - group: ""
    jsonPointers:
    - /data
    kind: Secret
    name: karpenter-cert
    namespace: karpenter
  project: default
  source:
    path: k/external-secrets-operator
    repoURL: https://github.com/amanibhavam/dotfiles
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: k3d-control-kyverno
  namespace: argocd
spec:
  destination:
    name: k3d-control
  ignoreDifferences:
  - group: ""
    jsonPointers:
    - /data
    kind: Secret
    name: karpenter-cert
    namespace: karpenter
  project: default
  source:
    path: k/kyverno
    repoURL: https://github.com/amanibhavam/dotfiles
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: k3d-control-pod-identity-webhook
  namespace: argocd
spec:
  destination:
    name: k3d-control
  ignoreDifferences:
  - group: ""
    jsonPointers:
    - /data
    kind: Secret
    name: karpenter-cert
    namespace: karpenter
  project: default
  source:
    path: k/pod-identity-webhook
    repoURL: https://github.com/amanibhavam/dotfiles
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  name: k3d-control-tfo
  namespace: argocd
spec:
  destination:
    name: k3d-control
  ignoreDifferences:
  - group: ""
    jsonPointers:
    - /data
    kind: Secret
    name: karpenter-cert
    namespace: karpenter
  project: default
  source:
    path: k/tfo
    repoURL: https://github.com/amanibhavam/dotfiles
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
