#ManagedBy: cue

patchesStrategicMerge: []
resources: []
helmCharts:
  - releaseName: bootstrap
    name: any-resource
    version: 0.1.0
    repo: https://kiwigrid.github.io
    valuesInline:
      anyResources:
        k3d-control-secrets: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-k3d-control-secrets
            annotations:
              argocd.argoproj.io/sync-wave: "1"
          spec:
            project: default
            destination:
              name: in-cluster
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/k3d-control-secrets
            syncPolicy:
              automated:
                prune: true
        cert-manager: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-cert-manager
            annotations:
              argocd.argoproj.io/sync-wave: "10"
          spec:
            project: default
            destination:
              name: in-cluster
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/cert-manager
            syncPolicy:
              automated:
                prune: true
        external-secrets: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-external-secrets
            annotations:
              argocd.argoproj.io/sync-wave: "10"
          spec:
            project: default
            destination:
              name: in-cluster
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/external-secrets
            syncPolicy:
              automated:
                prune: true
        kyverno: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-kyverno
            annotations:
              argocd.argoproj.io/sync-wave: "10"
          spec:
            project: default
            destination:
              name: in-cluster
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/kyverno
            syncPolicy:
              automated:
                prune: true
        argo-events: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-argo-events
            annotations:
              argocd.argoproj.io/sync-wave: "10"
          spec:
            project: default
            destination:
              name: in-cluster
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/argo-events
            syncPolicy:
              automated:
                prune: true
        knative: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-knative
            annotations:
              argocd.argoproj.io/sync-wave: "10"
          spec:
            project: default
            destination:
              name: in-cluster
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/knative
            syncPolicy:
              automated:
                prune: true
        kong: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-kong
            annotations:
              argocd.argoproj.io/sync-wave: "100"
          spec:
            project: default
            destination:
              name: in-cluster
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/kong
            syncPolicy:
              automated:
                prune: true
        hello: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-hello
            annotations:
              argocd.argoproj.io/sync-wave: "1000"
          spec:
            project: default
            destination:
              name: in-cluster
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/hello
            syncPolicy:
              automated:
                prune: true
    includeCRDs: true
