#ManagedBy: cue

patchesStrategicMerge: []
resources: []
helmCharts:
  - releaseName: bootstrap
    name: any-resource
    version: 0.1.0
    repo: https://kiwigrid.github.io
    valuesInline:
      anyResources:
        argo-cd: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-argo-cd
            annotations:
              argocd.argoproj.io/sync-wave: "1"
          spec:
            project: default
            destination:
              name: k3d-control
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/argo-cd
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
        cert-manager: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-cert-manager
            annotations:
              argocd.argoproj.io/sync-wave: "1"
          spec:
            project: default
            destination:
              name: k3d-control
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/cert-manager
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
        kyverno: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-kyverno
            annotations:
              argocd.argoproj.io/sync-wave: "1"
          spec:
            project: default
            destination:
              name: k3d-control
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/kyverno
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
        pod-identity-webhook: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-pod-identity-webhook
            annotations:
              argocd.argoproj.io/sync-wave: "10"
          spec:
            project: default
            destination:
              name: k3d-control
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/pod-identity-webhook
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
        external-secrets-operator: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-external-secrets-operator
            annotations:
              argocd.argoproj.io/sync-wave: "10"
          spec:
            project: default
            destination:
              name: k3d-control
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/external-secrets-operator
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
        argo-events: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-argo-events
            annotations:
              argocd.argoproj.io/sync-wave: "10"
          spec:
            project: default
            destination:
              name: k3d-control
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/argo-events
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
        karpenter: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-karpenter
            annotations:
              argocd.argoproj.io/sync-wave: "20"
          spec:
            project: default
            destination:
              name: k3d-control
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/karpenter
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
        k3d-control-secrets-store: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-secrets-store
            annotations:
              argocd.argoproj.io/sync-wave: "20"
          spec:
            project: default
            destination:
              name: k3d-control
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/k3d-control-secrets-store
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
        vc1: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-vc1
            annotations:
              argocd.argoproj.io/sync-wave: "30"
          spec:
            project: default
            destination:
              name: k3d-control
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/vc1
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
        vc2: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-vc2
            annotations:
              argocd.argoproj.io/sync-wave: "30"
          spec:
            project: default
            destination:
              name: k3d-control
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/vc2
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
        vc3: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-vc3
            annotations:
              argocd.argoproj.io/sync-wave: "30"
          spec:
            project: default
            destination:
              name: k3d-control
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/vc3
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
        vc4: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-vc4
            annotations:
              argocd.argoproj.io/sync-wave: "30"
          spec:
            project: default
            destination:
              name: k3d-control
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/vc4
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
        events: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-control-events
            annotations:
              argocd.argoproj.io/sync-wave: "100"
          spec:
            project: default
            destination:
              name: k3d-control
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/events
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
    includeCRDs: true
