# ManagedBy: cue

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vc3
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: dev
            namespace: default
            path: dev
            cluster: vc3
  template:
    metadata:
      name: vc3-{{name}}
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/defn/app
        path: k/{{path}}
        targetRevision: master
      destination:
        name: '{{cluster}}'
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
      ignoreDifferences:
        - kind: MutatingWebhookConfiguration
          group: admissionregistration.k8s.io
          name: vault-agent-injector-cfg
          jsonPointers:
            - /webhooks/0/clientConfig/caBundle
        - kind: MutatingWebhookConfiguration
          group: admissionregistration.k8s.io
          name: webhook.domainmapping.serving.knative.dev
          jsonPointers:
            - /webhooks/0/rules
        - kind: MutatingWebhookConfiguration
          group: admissionregistration.k8s.io
          name: webhook.serving.knative.dev
          jsonPointers:
            - /webhooks/0/rules
        - kind: ValidatingWebhookConfiguration
          group: admissionregistration.k8s.io
          name: validation.webhook.serving.knative.dev
          jsonPointers:
            - /webhooks/0/rules
        - kind: ValidatingWebhookConfiguration
          group: admissionregistration.k8s.io
          name: validation.webhook.domainmapping.serving.knative.dev
          jsonPointers:
            - /webhooks/0/rules
        - kind: Deployment
          group: apps
          name: kong-kong
          jsonPointers:
            - /spec/template/spec/tolerations
        - group: kyverno.io
          kind: ClusterPolicy
          jqPathExpressions:
            - .spec.rules[] | select(.name|test("autogen-."))
