# ManagedBy: cue

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: k3d-control-vc3
spec:
  destination:
    name: in-cluster
  source:
    repoURL: https://github.com/defn/app
    targetRevision: master
    path: e/vc3
  syncPolicy:
    automated:
      prune: true
