# ManagedBy: cue

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: k3d-control-vc1
spec:
  project: default
  destination:
    name: in-cluster
  source:
    repoURL: https://github.com/defn/app
    path: e/vc1
    targetRevision: master
