apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k3d-control-nons
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: kourier
            path: kourier
            cluster: in-cluster
  template:
    metadata:
      name: "k3d-control-{{name}}"
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/defn/app
        path: k/{{path}}
        targetRevision: master
      destination:
        name: "{{cluster}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
