apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: external-secrets
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: vcluster-global-vc0
          role: external-secrets
      path: kv
      server: http://100.121.162.1:8200
      version: v2
