# ManagedBy: cue

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
spec:
  generators:
    - list:
        elements:
          - name: kyverno
            namespace: kyverno
            path: kyverno
            cluster: k3d-circus
          - name: cert-manager
            namespace: cert-manager
            path: cert-manager
            cluster: k3d-circus
          - name: kuma-global
            namespace: kuma
            path: kuma-global
            cluster: k3d-circus
  template:
    metadata:
      name: k3d-circus-{{name}}
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/defn/app
        path: k/{{path}}
        targetRevision: master
      destination:
        name: '{{cluster}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
      ignoreDifferences:
        - kind: MutatingWebhookConfiguration
          group: admissionregistration.k8s.io
          name: vault-agent-injector-cfg
          jsonPointers:
            - /webhooks/0/clientConfig/caBundle
        - kind: MutatingWebhookConfiguration
          group: admissionregistration.k8s.io
          name: webhook.domainmapping.serving.knative.dev
          jsonPointers:
            - /webhooks/0/rules
        - kind: MutatingWebhookConfiguration
          group: admissionregistration.k8s.io
          name: webhook.serving.knative.dev
          jsonPointers:
            - /webhooks/0/rules
        - kind: ValidatingWebhookConfiguration
          group: admissionregistration.k8s.io
          name: validation.webhook.serving.knative.dev
          jsonPointers:
            - /webhooks/0/rules
        - kind: ValidatingWebhookConfiguration
          group: admissionregistration.k8s.io
          name: validation.webhook.domainmapping.serving.knative.dev
          jsonPointers:
            - /webhooks/0/rules
        - kind: Deployment
          group: apps
          name: kong-kong
          jsonPointers:
            - /spec/template/spec/tolerations
        - group: kyverno.io
          kind: ClusterPolicy
          jqPathExpressions:
            - .spec.rules[] | select(.name|test("autogen-."))
metadata:
  name: k3d-circus
  namespace: argocd
