#ManagedBy: cue

patchesStrategicMerge: []
resources: []
helmCharts:
  - releaseName: bootstrap
    name: any-resource
    version: 0.1.0
    repo: https://kiwigrid.github.io
    valuesInline:
      anyResources:
        kyverno: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-circus-kyverno
            annotations:
              argocd.argoproj.io/sync-wave: "10"
          spec:
            project: default
            destination:
              name: k3d-circus
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/kyverno
            syncPolicy:
              automated:
                prune: true
        k3d-circus-secrets: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-circus-secrets
            annotations:
              argocd.argoproj.io/sync-wave: "20"
          spec:
            project: default
            destination:
              name: k3d-circus
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/k3d-circus-secrets
            syncPolicy:
              automated:
                prune: true
        kuma-global: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-circus-kuma-global
            annotations:
              argocd.argoproj.io/sync-wave: "30"
          spec:
            project: default
            destination:
              name: k3d-circus
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/kuma-global
            syncPolicy:
              automated:
                prune: true
        mesh: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-circus-mesh
            annotations:
              argocd.argoproj.io/sync-wave: "40"
          spec:
            project: default
            destination:
              name: k3d-circus
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/mesh
            syncPolicy:
              automated:
                prune: true
        demo2: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            namespace: argocd
            name: k3d-circus-demo2
            annotations:
              argocd.argoproj.io/sync-wave: "100"
          spec:
            project: default
            destination:
              name: k3d-circus
            source:
              repoURL: https://github.com/defn/app
              targetRevision: master
              path: k/demo2
            syncPolicy:
              automated:
                prune: true
    includeCRDs: true
