apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::319951235442:role/meh
    eks.amazonaws.com/sts-regional-endpoints: "true"
    eks.amazonaws.com/token-expiration: "3600"
  name: hello
  namespace: default
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hello
  namespace: default
spec:
  dataFrom:
  - extract:
      key: hello/earth
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    name: hello
    template:
      data:
        meh: '{{ .meh | toString }}'
        world: '{{ .world | toString }}'
---
apiVersion: v1
kind: Pod
metadata:
  name: hello
  namespace: default
spec:
  containers:
  - args:
    - sudo apt update; sudo apt install -y awscli; aws sts get-caller-identity | sudo
      tee /mnt/hello.txt; sleep infinity
    command:
    - bash
    - -c
    image: ghcr.io/defn/dev:latest-nix-installed
    name: hello
    volumeMounts:
    - mountPath: /mnt/hello
      name: hello
      readOnly: true
  serviceAccountName: hello
  volumes:
  - name: hello
    secret:
      optional: false
      secretName: hello
