apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    networking.knative.dev/visibility: cluster-local
  annotations:
    networking.knative.dev/ingress.class: kong
  name: helm-b
  namespace: default
spec:
  template:
    spec:
      containerConcurrency: 0
      containers:
      - name: whoami
        image: containous/whoami:latest
        ports:
        - containerPort: 80
  traffic:
  - latestRevision: true
    percent: 100