#ManagedBy: cue

metadata:
  name: combo-breaker
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: default
      containers:
        - name: meh
          image: ubuntu
          command:
            - bash
            - -c
          args:
            - |-
              set -exfu
              apt update
              apt upgrade -y
              apt install -y kubectl jq
              kubectl get tf egg -o yaml
      restartPolicy: Never
kind: Job
apiVersion: batch/v1
