#ManagedBy: cue

metadata:
  name: combo-breaker
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: default
      containers:
        - name: meh
          image: ubuntu
          command:
            - bash
            - -c
          args:
            - |-
              set -exfu
              apt-get update
              apt-get upgrade -y
              apt-get install -y ca-certificates curl
              apt-get install -y apt-transport-https
              curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
              echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list
              apt-get update
              apt-get install -y kubectl jq
              test "completed" == "$(kubectl get tf egg -o json | jq -r '.status.phase')"
      restartPolicy: Never
kind: Job
apiVersion: batch/v1
