#ManagedBy: cue

metadata:
  name: combo-breaker
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: meh
          image: ubuntu
          command:
            - "false"
      restartPolicy: Never
kind: Job
apiVersion: batch/v1
