apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  name: dry-brine-chicken
  namespace: default
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - args:
        - "set -exfu\napt-get update\napt-get upgrade -y\napt-get install -y ca-certificates
          curl\napt-get install -y apt-transport-https\ncurl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg
          https://packages.cloud.google.com/apt/doc/apt-key.gpg\necho \"deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg]
          https://apt.kubernetes.io/ kubernetes-xenial main\" | tee /etc/apt/sources.list.d/kubernetes.list\napt-get
          update\napt-get install -y kubectl jq\nfor a in rocky rosie; do\n\ttest
          \"completed\" == \"$(kubectl get tf \"$a\" -o json | jq -r '.status.phase')\"\ndone"
        command:
        - bash
        - -c
        image: ubuntu
        name: meh
      restartPolicy: Never
      serviceAccountName: default
---
apiVersion: tf.isaaguilar.com/v1alpha2
kind: Terraform
metadata:
  name: bonchon
  namespace: default
spec:
  backend: "terraform {\n\tbackend \"kubernetes\" {\n\t\tin_cluster_config = true\n\t\tsecret_suffix
    \    = \"bonchon\"\n\t\tnamespace         = \"default\"\n\t}\n}"
  ignoreDelete: true
  keepLatestPodsOnly: true
  outputsToOmit:
  - "0"
  scmAuthMethods: []
  serviceAccount: default
  terraformModule:
    source: https://github.com/defn/app.git//tf/m/fried-chicken?ref=master
  terraformVersion: 1.0.0
