#ManagedBy: cue

patchesStrategicMerge: []
resources: []
namespace: kyverno
helmCharts:
  - releaseName: kyverno
    name: kyverno
    version: 2.5.2
    repo: https://kyverno.github.io/kyverno
    namespace: kyverno
    valuesInline:
      replicaCount: 1
    includeCRDs: true
