#ManagedBy: cue

patchesStrategicMerge: []
resources:
  - resource-namespace-kyverno.yaml
namespace: kyverno
helmCharts:
  - releaseName: kyverno
    name: kyverno
    version: 2.5.5
    repo: https://kyverno.github.io/kyverno
    namespace: kyverno
    valuesInline:
      replicaCount: 1
    includeCRDs: true
