#ManagedBy: cue

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kuma-tls-cert
  namespace: kuma
spec:
  target:
    name: kuma-tls-cert
    template:
      data:
        tls.crt: !!binary e3sgaW5kZXggLiAidGxzLmNydCIgfX0=
        tls.key: !!binary e3sgaW5kZXggLiAidGxzLmtleSIgfX0=
        ca.crt: !!binary e3sgaW5kZXggLiAiY2EuY3J0IiB9fQ==
  dataFrom:
    - extract:
        key: /dev/k3d-smiley/kuma-zone
  refreshInterval: 60s
  secretStoreRef:
    name: dev
    kind: ClusterSecretStore
