#ManagedBy: cue

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kds-ca-certs
  namespace: kuma
spec:
  target:
    name: kds-ca-certs
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .cert }}"
        tls.key: "{{ .key }}"
  dataFrom:
    - extract:
        key: /dev/k3d-smiley/kuma-zone
  refreshInterval: 60s
  secretStoreRef:
    name: dev
    kind: ClusterSecretStore
