namespace: vc2

helmCharts:
- releaseName: vcluster
  name: vcluster
  namespace: vc2
  version: 0.12.1
  repo: https://charts.loft.sh
  includeCRDs: true
  valuesInline:
    service:
      type: ClusterIP
    vcluster:
      image: rancher/k3s:v1.23.10-k3s1
    syncer:
      extraArgs:
        - --tls-san=vcluster.vc2.svc.cluster.local
        - --enforce-toleration=env=vc2:NoSchedule
    sync:
      nodes:
        enabled: true
        nodeSelector: "env=vc2"
    tolerations:
      - key: env
        value: vc2
        operator: Equal
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: env
              operator: In
              values:
              - vc2
