apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: defn
spec:
  template:
    spec:
      githubAPICredentialsFrom:
        secretRef:
          name: controller-manager
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: defn
spec:
  githubAPICredentialsFrom:
    secretRef:
      name: controller-manager
