apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: defn
spec:
  replicas: 1
  template:
    spec:
      githubAPICredentialsFrom:
        secretRef:
          name: controller-manager
      organization: defn
      dockerdWithinRunnerContainer: true