#ManagedBy: cue

apiVersion: batch/v1
kind: Job
metadata:
  name: blocker
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: sleeping
          image: ubuntu
          command:
            - sleep
            - "10"
