apiVersion: kuma.io/v1alpha1
kind: ExternalService
mesh: default
metadata:
  namespace: default
  name: google
spec:
  tags:
    kuma.io/service: google
    kuma.io/protocol: http
  networking:
    address: google.com:80
    tls:
      enabled: false