# env KUMA_MODE=zone KUMA_MULTIZONE_ZONE_NAME=pod KUMA_MULTIZONE_ZONE_GLOBAL_ADDRESS=grpcs://100.64.110.16:5685 KUMA_MULTIZONE_ZONE_KDS_ROOT_CA_FILE=$HOME/app/k/kuma-global/ca.crt kuma-cp run
# global apply -f universal.yaml
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  name: default
spec:
  mtls:
    enabledBackend: ca-1
    backends:
      - name: ca-1
        type: builtin
        mode: STRICT
        dpCert:
          rotation:
            expiration: 1d
        conf:
          caCert:
            RSAbits: 2048
            expiration: 10y
