#ManagedBy: cue

namespace: external-secrets
patchesStrategicMerge: []
resources: []
helmCharts:
  - releaseName: external-secrets
    name: external-secrets
    namespace: external-secrets
    version: 0.5.8
    repo: https://charts.external-secrets.io
    valuesInline:
      webhook:
        create: false
      certController:
        create: false
    includeCRDs: true
