#ManagedBy: cue

patchesStrategicMerge: []
resources: []
namespace: external-secrets
helmCharts:
  - releaseName: external-secrets
    name: external-secrets
    version: 0.5.8
    repo: https://charts.external-secrets.io
    namespace: external-secrets
    valuesInline:
      webhook:
        create: false
      certController:
        create: false
    includeCRDs: true
