#ManagedBy: cue

patchesStrategicMerge: []
resources:
  - resource-namespace-external-secrets.yaml
  - resource-cluster-secret-store-dev.yaml
  - resource-cluster-role-binding-delegator.yaml
namespace: external-secrets
helmCharts:
  - releaseName: external-secrets
    name: external-secrets
    version: 0.6.0
    repo: https://charts.external-secrets.io
    namespace: external-secrets
    valuesInline:
      webhook:
        create: true
      certController:
        create: true
    includeCRDs: true
