#ManagedBy: cue

patchesStrategicMerge: []
resources:
  - resource-namespace-kuma.yaml
namespace: kuma
helmCharts:
  - releaseName: kuma
    name: kuma
    version: 1.8.0
    repo: https://kumahq.github.io/charts
    namespace: kuma
    valuesInline:
      controlPlane:
        mode: zone
        zone: control
        kdsGlobalAddress: grpcs://100.64.110.16:5685
        tls:
          general:
            secretName: kuma-tls-cert
            caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURhVENDQWxHZ0F3SUJBZ0lSQUw0cEVzblptNE9wSlBmTTg0MnlPYzB3RFFZSktvWklodmNOQVFFTEJRQXcKSWpFZ01CNEdBMVVFQXhNWGEzVnRZUzFqYjI1MGNtOXNMWEJzWVc1bExtdDFiV0V3SGhjTk1qSXhNREEwTURZMApPRFV5V2hjTk16SXhNREF4TURZME9EVXlXakFpTVNBd0hnWURWUVFERXhkcmRXMWhMV052Ym5SeWIyd3RjR3hoCmJtVXVhM1Z0WVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTHRvdGFucnBGR1MKa0dSNVE0VVFMcDZvSktxOUpTSGwyTjhlZktrMGZUcytZK3lBL3puTlVHZ09rcmtYM0ZndXFmRTVGaE0xa1hHQQpEdzZNS1FnNzc1L3FreURsNDg0YmpPUmNLcHY5YWtqeHE4RHJYQ3YxNlpHbWZTVUZ1cExHRHBFS2VhSkRZZVBWCjB4TkpOS2RBWTBLWGdnTnczRmYzazBLYXgxNnFjdkMvVGhvODc5UFBybC9UTndmTVIvVzV4ZXIvUlZCaWdpUm0KQlJzVTYyWi9aRDliOTc3bjFoRjdHN2w0N1gwajM0dHB0Y2wrUDRPZ3NhenY2LzI3RGkrL09xRFlWT0xWdlJMaQpKRzdYVVcydmh5OC9lSDE2ZUR3US9YOGR5U0tTRlprOFZUWFBhbzkzMG9qN1EzQlB6dHhMZXZRSmRuL3dCdGMrCmIxSllKcGRwa3A4Q0F3RUFBYU9CbVRDQmxqQU9CZ05WSFE4QkFmOEVCQU1DQXFRd0V3WURWUjBsQkF3d0NnWUkKS3dZQkJRVUhBd0V3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVc1AzdEl6NU0yVkxieHpmdAowWWNqaDdSWHR4WXdQd1lEVlIwUkJEZ3dOb0lYYTNWdFlTMWpiMjUwY205c0xYQnNZVzVsTG10MWJXR0NHMnQxCmJXRXRZMjl1ZEhKdmJDMXdiR0Z1WlM1cmRXMWhMbk4yWXpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQUlZSngKMFFPUDNvQktuWG5aUXlRMlUwNnQ0MkEyRmxwTnhzNWpFVEpXVGVHSXhzekhrMW5VYk9WZ0xLQUxKcjBlK1ArbQpwZlNzZitMaGhjZTMrbk01VHlaK3Z2bTc2L2xJL0lqUk9kNktSL2MrVmt6WjBrMFVJK0kzR1pVeUlpZVNuQkxpCmduMXFHRlZRSFZnOUQvMEVtZW54bkN3aUNqRzVwbkEyQm9aeCt4YTB6bG4zZHRLUUlXbTRzdU92UHFEa0tMM1AKMDZvRm9ndDlqSlQwNlNQNmNRY3VUeWYwMVdDQVozM25WajNDb05SQ2pKNThnMW9HQ2p2MmdXb3NSemlBVU5GLwpUN0kvQ2c3UWNxOVZ6Z3EwSEtGNXVyajNuYUVsOGRWMzhURDcvKzdjSmRhNDRkcHdRNWdldXV3RCtkVWdxd2Q5ClV0MlE1ZlFmd0dpbVo5bUxYUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
          kdsZoneClient:
            secretName: kds-ca-certs
      ingress:
        enabled: true
      egress:
        enabled: true
    includeCRDs: true
