namespace: kuma

helmCharts:
- releaseName: kuma
  name: kuma
  namespace: kuma
  version: 1.8.0
  repo: https://kumahq.github.io/charts
  includeCRDs: true
  valuesInline:
    controlPlane:
      mode: zone
      zone: grove
      kdsGlobalAddress: grpcs://100.64.110.16:5685
      tls:
        general:
          secretName : generic-tls-certs
          caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURhVENDQWxHZ0F3SUJBZ0lSQU1YT2hrRGNQL2hZZ3R6OXhwNjZqSWd3RFFZSktvWklodmNOQVFFTEJRQXcKSWpFZ01CNEdBMVVFQXhNWGEzVnRZUzFqYjI1MGNtOXNMWEJzWVc1bExtdDFiV0V3SGhjTk1qSXhNREEwTURNeApNek14V2hjTk16SXhNREF4TURNeE16TXhXakFpTVNBd0hnWURWUVFERXhkcmRXMWhMV052Ym5SeWIyd3RjR3hoCmJtVXVhM1Z0WVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT0l5RmpEeHViczEKcU5JODlndDcwc0VLc2RKQjA4R2VpM1RSeE8vRElKK2FFSFdRNW9xQ1JiUmNZUnN1MG9KTTFlQ0hxVko5eFF6UQo3TXdmWVFJRmp3M3k5ZDhzUXVzaXh2bDkxZXVLRS8yQWhQTENFeTcxcWxvNm51M1dER2VWM1FZdG02eE5Ib3dlClBON3VnMXVkdFBJZlBvSUdoUzUzZnIyK2E0Wi9CaSs1ekVSM21FaEd2RnNEY2M0UzR0MUlyalY1NHJmOWNrWTgKV1FHdWtpYXVYSFZwazk3UFUwbWN4S0l1U3RlejFFY1RYbTZpY0syM3I5bk9WUU82dUFORnpuU21wQlRZdzJzNwpyVUlyQ25oNXA5KzJzRVEwNUIwWnhYckd6cjhGK1d2QTJYeXBvZjNsdkh3OTBHVFlna3FEYnJGQzh6dUNzWXpzCjgwK2VOc2piMnBjQ0F3RUFBYU9CbVRDQmxqQU9CZ05WSFE4QkFmOEVCQU1DQXFRd0V3WURWUjBsQkF3d0NnWUkKS3dZQkJRVUhBd0V3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVQStWS3lwWDJzZkdMUnVQcwplT1dCN2ZPbFhKSXdQd1lEVlIwUkJEZ3dOb0lYYTNWdFlTMWpiMjUwY205c0xYQnNZVzVsTG10MWJXR0NHMnQxCmJXRXRZMjl1ZEhKdmJDMXdiR0Z1WlM1cmRXMWhMbk4yWXpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQUxzWkkKaGxhNitsd0hEVWw3Sm5VcHBoenBNZ0RLVWg5QW80blIvQzB1WnZoRjZldllaT0lvSmhuZ0huNlhieWZNd1cwbApPdlB5ZWIwUEw0d0ovYWMwRmI2ZnNSelJpM05HMnF6YisrV1U1cTZIOVNLRnJkdnRLakNLdXdxL25XUy9MMisvCnZ2YmlwOEpsdVlsK2Fjd3k4Nmw0OWszRmlUa24wQ21zME9uRGxsV1VhWnpZTTdRcXY4R1FPWUduTXpGWkVNSkMKcE01a1hDOUtEdlAzVDVWMWpRTnlpZ2lFeHdCQkg3VGE5ZDZUeXZIeGtxelltWW9jaHcvbkh1dWlxWkRQaW1EaQo0YS8xRnYyQ1Y5SWdGcDNpNWVicW04MkR6cUs0d3BrMktkZllYS21iTmY1cm4yQnJlRjJoS0VvRW5XZ29kT0hBCmMxdXAzNVY3UjN3dG54Z3pYQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    ingress:
      enabled: true
    egress:
      enabled: true