namespace: datadog

helmCharts:
- releaseName: datadog
  name: datadog
  version: 3.1.1
  repo: https://helm.datadoghq.com
  includeCRDs: true
  valuesInline:
    clusterAgent:
      enabled: "true"
      metricsProvider:
        enabled: "true"
      processAgent:
        enabled: "trie"
    datadog:
      logs:
        enabled: true
        containerCollectAll: true
      appKeyExistingSecret: datadog-app-secret
      apiKeyExistingSecret: datadog-api-secret
