#ManagedBy: cue

patchesStrategicMerge: []
resources:
  - resource-namespace-datadog.yaml
namespace: datadog
helmCharts:
  - releaseName: datadog
    name: datadog
    version: 3.1.1
    repo: https://helm.datadoghq.com
    namespace: datadog
    valuesInline:
      clusterAgent:
        enabled: "true"
        metricsProvider:
          enabled: "true"
        processAgent:
          enabled: "false"
      targetSystem: linux
      datadog:
        logs:
          enabled: true
          containerCollectAll: true
        appKeyExistingSecret: datadog-app-secret
        apiKeyExistingSecret: datadog-api-secret
    includeCRDs: true
