apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
spec:
  jetstream:
    version: latest
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: default
spec:
  resource:
    example:
      namespace: default
      group: ""
      version: v1
      resource: configmaps
      eventTypes:
        - ADD
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: default
spec:
  dependencies:
    - name: input
      eventSourceName: default
      eventName: example
  triggers:
    - template:
        name: run-this
        k8s:
          operation: create
          source:
            resource:
              apiVersion: v1
              kind: Pod
              metadata:
                generateName: run-this-
                namespace: default
              spec:
                containers:
                  - name: workspace
                    image: 169.254.32.1:5000/workspace
                    command:
                      - bash
                      - -c
                    args:
                      - "echo hello-world"
          parameters:
            - src:
                dependencyName: input
                dataTemplate: "{{ .Input.body.data.script}}"
              dest: spec.containers.0.args.0
